sheet:
  csv_name: None
  header_language: german
personal:
  weekly_worktime: 15:00
email:
  sender: julius.schlensok@mitsm.de
  receiver: renate.wagner@mitsm.de
  body: Dies ist eine automatisierte Email, an die Julius' Arbeitszeit angeh√§ngt wird. Probleme/Feedback bitte an feedback@schlensok.org
  smtp_server: smtp.office365.com
  name: Julius Schlensok